CREATE TABLE leads (
    id VARCHAR(36) PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    company VARCHAR(100),
    job_title VARCHAR(100),
    employees INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE attribution (
    id VARCHAR(36) PRIMARY KEY,
    lead_id VARCHAR(36) NOT NULL UNIQUE,
    source VARCHAR(100) NOT NULL,
    campaign VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE
);

CREATE TABLE lead_score (
    id VARCHAR(36) PRIMARY KEY,
    lead_id VARCHAR(36) NOT NULL UNIQUE,
    total_score INTEGER DEFAULT 0 NOT NULL,
    is_mql BOOLEAN DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE
);